"""add raw_text to resumes

Revision ID: cdf3df93ba88
Revises: 894dc37b2dcf
Create Date: 2026-09-21 17:23:28.880450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf3df93ba88'
down_revision: Union[str, Sequence[str], None] = '894dc37b2dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'raw_text')
    # ### end Alembic commands ###
